# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: South Green Trainings Web Site
email: christine.tranchant@ird.fr
description: Bioinformatics trainings, Linux, HPC, NGS, NGS workflow manager, TOGGLe, galaxy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/SouthGreenPlatform/trainings/tree/gh-pages/" # the base hostname & protocol for your site, e.g. http://example.com
repository_url: "https://github.com/SouthGreenPlatform/trainings.git"
version: 0.1


# authors
authors:
  ravel:
    name: SÃ©bastien RAVEL
    display_name: Sebastien RAVEL
    email: sebastien.ravel@cirad.fr
  tranchant:
    name: Christine Tranchant-Dubreuil
    display_name: Christine Tranchant-Dubreuil
    email: christine.tranchant@ird.fr

# Build settings
theme:  jekyll-theme-slate
#theme:  minima

# Where things are
source:       .
destination:  ./_site
#plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
highlighter: rouge
collections:
  posts:
    output:   false

# Handling Reading
safe:         false
include:      [".htaccess","_pages"]
exclude:      ["Gemfile","Gemfile.lock"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    toggle.ird.fr
show_dir_listing: false

# Outputting
permalink:     /home/
paginate_path: /page:num
timezone:      null

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  syntax_highlighter: rouge
